language: node_js
node_js:
  - 8.11.3
install:
  - npm install
  - npm run build
  - npm install -g firebase-tools
after_success:
  - firebase-ci deploy
branches:
  only:
    - master
script:
  - echo "Deploy"
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT